services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:debian
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: kennycallado/q-api-store-demo:latest
    command:
      - -A
      - --no-banner
      - --user=root
      - --pass=root
      - --bind=0.0.0.0:8000

  super:
    image: kennycallado/q-api-super:latest
    network_mode: service:db
    environment:
      DB_HOST: 'localhost:8000'

  auth:
    image: kennycallado/q-api-auth:latest
    network_mode: service:db
    environment:
      ROCKET_PORT: 9000
      ROCKET_DATABASES: '{store={host="localhost", port=8000, username="root", password="root"}}'
      ROCKET_SECRET_KEY: 'xdOXN1pEDSi3TYupqi7jOtXwaa3rOfClDPuW3HzMdkU='
