services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  app:
    container_name: app
    image: kennycallado/q-app-php:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      ENVIRONMENT: development
      DATABASE_URL: http://surrealdb:8000/sql
      AUTH_URL: http://auth:9000/auth
    volumes:
      - .:/var/www/html

  surrealdb:
    container_name: surrealdb
    image: surrealdb/surrealdb:v1.4.2
    restart: unless-stopped
    ports:
      - 8000:8000
    command: 
      - start
      - memory
      - -A
      - --auth
      - --no-banner
      # - --log=trace
      # - --log=info
      - --user=root
      - --pass=root
      - --bind=0.0.0.0:8000

  auth:
    container_name: auth
    image: kennycallado/q-api-auth:latest
    pull_policy: "always"
    ports:
      - 9000:9000
    environment:
      ROCKET_PORT: 9000
      ROCKET_DATABASES: '{store={host="surrealdb", port=8000, username="root", password="root"}}'
      ROCKET_SECRET_KEY: 'xdOXN1pEDSi3TYupqi7jOtXwaa3rOfClDPuW3HzMdkU='

  super:
    container_name: super
    image: kennycallado/q-api-super:latest
    pull_policy: "always"
    restart: unless-stopped
    environment:
      DB_HOST: surrealdb:8000
