services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: kennycallado/q-api-store-demo:latest
    restart: unless-stopped
    command: 
      - start
      - memory
      - -A
      - --auth
      - --no-banner
      - --user=root
      - --pass=root
      - --bind=0.0.0.0:8000

  super:
    image: kennycallado/q-api-super:latest
    restart: unless-stopped
    pull_policy: "always"
    network_mode: service:db
    environment:
      DB_HOST: localhost:8000
