services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    # image: surrealdb/surrealdb:v1.4.2
    image: kennycallado/q-api-store-demo:latest
    restart: unless-stopped
    command: 
      - start
      - memory
      - -A
      - --auth
      - --no-banner
      # - --log=trace
      # - --log=info
      - --user=root
      - --pass=root
      - --bind=0.0.0.0:8000

  super:
    image: kennycallado/q-api-super:latest
    restart: unless-stopped
    pull_policy: "always"
    network_mode: service:db
    environment:
      DB_HOST: localhost:8000

  auth:
    image: kennycallado/q-api-auth:latest
    pull_policy: "always"
    network_mode: service:db
    environment:
      ROCKET_PORT: 9000
      ROCKET_DATABASES: '{store={host="localhost", port=8000, username="root", password="root"}}'
      ROCKET_SECRET_KEY: 'CKyYHQ3ttfxKcXN7UqPOZd5Lu4XvVBFYMkUG6WsVNyE='
