services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: kennycallado/q-api-store-demo:latest
    restart: unless-stopped
    command: 
      - -A
      - --auth
      - --no-banner
      - --user=root
      - --pass=root
      - --bind=0.0.0.0:8000

  super:
    image: kennycallado/q-api-super:latest
    network_mode: service:db
    environment:
      DB_HOST: 'localhost:8000'
