services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    extends:
      file: ../docker-compose.yml
      service: db

  super:
    extends:
      file: ../docker-compose.yml
      service: super
